version: '3'

services:
  mongo-express:
#    env_file:
#      - mongo-docker.env
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: express
      ME_CONFIG_BASICAUTH_PASSWORD: opens
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: opens
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
#    env_file:
#      - mongo-docker.env    
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: opens
    ports:
      - "27018:27017"
    volumes:
        - /home/ubuntu/mongo/data:/data/db
    networks:
      - mongo-compose-network

networks:
    mongo-compose-network:
      driver: bridge
